### ISSUE TITLE
Huawei Sdk

### ISSUE THREAD

**Issue by niktses** [OneSignal/OneSignal-Android-SDK#1080]
I have been using the android and ios sdk for a long time.

today I added the huawei sdk and i get this an the report:
Failed (Errored)

Android and ios gets the notifications like always.

It has confirmed my huawei device and i have followed everything here:
https://documentation.onesignal.com/docs/huawei-sdk-setup.

it doesnt seem to me like an error from the android code but i have nothing else to identify the issue.

**Comment by jkasten2** [comment]
@niktses Can you send a test notification to only your Huawei devices, to confirm the "Failed (Errored)" isn't from an iOS or Android device? After you confirm this I recommend sending a notification with only a title and message body. If a basic notification works then I recommend adding each customization option one at a time, send a test notification in between.

You can also reach out to OneSignal support while signed into the OneSignal dashboard, they can help investigate the error.

**Comment by niktses** [comment]
That is exactly what i did. Only title sent only to hms and it fails. The credentials seem to be fine since my devices showed when i completed the steps for huawei.

**Comment by jkasten2** [comment]
@niktses The Huawei credentials you enter on the OneSignal dashboard are only used for sending pushes. However OneSignal also connects to Huawei with them on save to ensure they are correct.

Since the device is showing as subscribed on the OneSignal dashboard then you have most likely setup the SDK correctly. Since it is a send issue I recommend contacting OneSignal support so they can look into the error from the backend side of things.

**Comment by jkasten2** [comment]
@niktses This issue has been resolve on the OneSignal backend now. It was an issue limited to sending Huawei (HMS) notifications to some devices.

**Comment by niktses** [comment]
Yes it seems to be working now. Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
