### ISSUE TITLE
OneSignal causes extra "*.permission.C2D_MESSAGE" permissions to be declared which prevents different flavours of the same app being installed simultaneously 

### ISSUE THREAD

**Issue by gerbiljames** [OneSignal/OneSignal-Android-SDK#110]
It seems to me that declaring `manifestApplicationId` in build.gradle and having OneSignal use that to generate the permission declarations is causing permissions to be declared both with and without any added `applicationIdSuffix`. This means that it is impossible to install different flavours of the same app as Android doesnt allow permissions to be redeclared. Using `${applicationId}` in OneSignals manifest in place of `${manifestApplicationId}` corrects this behavior, is there any reason why `manifestApplicationId` is needed?

**Comment by jkasten2** [comment]
@gerbiljames Our [AndroidManifest.xml](https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/release/AndroidManifest.xml#L3-L5) uses `${manifestApplicationId}` instead of `${applicationId}` as gradle was replacing it with `com.onesignal` in the final `AndroidManifest.xml` bundled our release AAR file.

From a quick test it seems this gradle issue has been fixed for library projects. I'll do a bit more testing on this and report back.

Feel free to leave your .gradle file reproducing the issue as well.

**Comment by gerbiljames** [comment]
Thanks for looking into it for me. Here's my [build.gradle](https://gist.github.com/gerbiljames/66599b44d7a21b460061d9f3666aefa2) (with some info removed).  I can't install the dev buildtype at the same time as the beta or release.

**Comment by jkasten2** [comment]
@gerbiljames This should now be fixed in version [3.3.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.3.0).
