### ISSUE TITLE
Huawei payload empty

### ISSUE THREAD

**Issue by janbolat** [OneSignal/OneSignal-Android-SDK#1108]
Hi,
using 3.15.2
```
    googleImplementation 'com.onesignal:OneSignal:3.15.2'
    huaweiImplementation('com.onesignal:OneSignal:3.15.2') {
        exclude group: 'com.google.android.gms'
        exclude group: 'com.google.firebase'
    }
    huaweiImplementation 'com.huawei.hms:push:5.0.0.300'
```

The problem is that payload is empty in `notificationOpened()` in my custom open handler which implements `OneSignal.NotificationOpenedHandler`.

![image](https://user-images.githubusercontent.com/6511056/89275456-1b38c380-d664-11ea-9438-9e53f3ae390e.png)

* Messages are sent through OneSignal web-site.
* Also tried to forward with `OneSignalHmsEventBridge`, but no luck.
* Title and body of the message in notification drawer is displayed without problems.

**Comment by janbolat** [comment]
It works great when I send a message with title, body and picture to Huawei Device:

[NotificationBundleProcessor.java](https://github.com/OneSignal/OneSignal-Android-SDK/blob/97791c996305a2d8bb0f63714e6b320d3566ecfc/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java#L347)

![image](https://user-images.githubusercontent.com/6511056/89307773-47b80400-d693-11ea-89f7-97573505f316.png)

![image](https://user-images.githubusercontent.com/6511056/89307713-37078e00-d693-11ea-99bb-ac1347c1d2ed.png)

**Comment by janbolat** [comment]
This is what happens when I send only a title and body to Huawei Device:

![image](https://user-images.githubusercontent.com/6511056/89308256-dcbafd00-d693-11ea-8ffe-5e211805ca35.png)
![image](https://user-images.githubusercontent.com/6511056/89308226-d4fb5880-d693-11ea-85b8-e8b4e9f87e46.png)

**Comment by janbolat** [comment]
Seems that [](https://github.com/OneSignal/OneSignal-Android-SDK/blob/18103b832d98280e9cd2a617bc62c415f1f0456c/OneSignalSDK/onesignal/src/main/java/com/onesignal/HmsMessageServiceOneSignal.java#L45) `onMessageReceived` not called() when sending only a title and body.

**Comment by jkasten2** [comment]
@janbolat Thanks for reporting and providing full details.

The root of the issue has to due with which [HMS message type](https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/push-introduction#h1-1576132561387) the push is sent with. OneSignal by default uses the HMS Notification Message type. However since it doesn't support Android's big picture feature we switch to using HMS's Data message type.

OneSignal uses the  HMS Notification Message type by default has it has the highest reliability. HMS Data messages may not be delivered if the app on the device has been force stopped.

The default HMS message types also explains the different amount of data you are seeing from the  OneSignal's `notificationOpened` and HMS's `onMessageReceived` events. If you need to take action on something on the push payload please use OneSignal's additional data as this will be accessible on both HMS message types.

**Comment by janbolat** [comment]
Thank you.
