### ISSUE TITLE
Using another back-end doesn't trigger any events when sending a notification

### ISSUE THREAD

**Issue by Bhullnatik** [OneSignal/OneSignal-Android-SDK#1157]
**Description:**

I'm using another back-end (customer.io) to send push notifications to my users. 
Although the notification is displayed correctly when sent through the other back-end, I don't receive any event about the notification being received and/or opened. It works fine when the push comes from OneSignal.

**Environment**
I tested on **OneSignal** v3.13.0 (as low as the Gradle plugin allowed me) & v3.15.3 (latest)
I can reproduce on Android versions 28, 29 & 30, both on emulators & physical devices.

Gradle:

```
    /build.gradle:
    classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.8, 0.99.99]'

    /app/build.gradle:
    implementation "com.onesignal:OneSignal:[3.15.0, 3.99.99]"
```

**Steps to Reproduce Issue:**

1. Add the OneSignal SDK
1. Send a push notification with the same Google project with another back-end

**Anything else:**

I don't rule out an error on my side, and I'm not entirely sure it's possible but the [`filterOtherGcmReceivers`](https://documentation.onesignal.com/docs/android-native-sdk#filterothergcmreceivers) documentation says: 
> Other non-OneSignal payloads will still be passed through so your app can handle FCM / GCM payloads from other back-ends.

I don't know how the payloads are supposed to be passed through, but I don't receive any event in the `NotificationReceivedHandler` nor the `NotificationOpenedHandler`.
If I register another receiver `com.google.firebase.MESSAGING_EVENT` `Service`, it does receive the event in `onMessageReceived()` if the notification is from OneSignal, but not from the other back-end. Same with extending [`NotificationExtenderService` & `onNotificationProcessing()`](https://documentation.onesignal.com/docs/service-extensions#android-notification-extender-service).

**Comment by Jeasmine** [comment]
The OneSignal SDK is designed to only handle pushes from OneSignal. So in your case, they need to follow customer.io's documentation on how to handle their notifications.

filterOtherGcmReceivers isn't what you need, and is going away in the 4.0.0 release. It doesn't work on Android 9+. It was to prevent OneSignal notifications from creating events in other notification SDKs but due to the changes in Google play services, this is no longer possible.

You will need to receive the notifications and call OneSignal methods available to interact with OneSignal
