### ISSUE TITLE
After the device turns off the screen for 1 minute, the app still get push notification, after 3 minutes onwards the app doesn't get push notification until waking up the device (I have set content_available = true) but still not successful.

### ISSUE THREAD

**Issue by suusofttruongnv** [OneSignal/OneSignal-Android-SDK#1165]
### **Please help me get rid of this problem:**
My application is using Onesignal ver 3.14.0 and I have 2 issues that need help

**1.After the device turns off the screen for 1 minute, the app still get push notification, after 3 minutes onwards the app doesn't get push notification until waking up the device (I have set content_available = true) but still not successful.**
This is the code I use to post the notice:

```
OneSignal.postNotification(new JSONObject("{'headings': {'en':'" + headings + "'}, 'contents': {'en':'" + message.getBody() + "'}, 'include_player_ids': " + userPlayerIds.toString() + ",'data': " + new Gson().toJson(messagePlayerIds) + ",'android_group':" + message.getChatId() + ",'android_channel_id':'4c1dce09-4dc6-4bce-b6c9-a25a5744e7f9'"+ ",'content_available':'true'" + " }"),
                       new OneSignal.PostNotificationResponseHandler() {
                           @Override
                           public void onSuccess(JSONObject response) {
                               Log.e(TAG,"OneSignalExample postNotification Success: " + response.toString());
                           }

                           @Override
                           public void onFailure(JSONObject response) {
                               Log.e(TAG,"OneSignalExample" + " postNotification Failure: " + response.toString());
                           }
                       });
```

_I already know that android system will kill services in sleep state, is there any way for Onesignal to function like FirebaseMessagingService?_

**2.The device receives multiple push notifications from the same user, when I press delete, all notifications are deleted, but the last message from the previous person reappears**

For example, you receive one message: message 1, ... 20. after deleting all, the message "message 20" reappears
please see image : 
![](https://user-images.githubusercontent.com/50869056/94339876-a6608500-0027-11eb-9e03-493e960f5127.png)

**### Please help me with the above 2 problems, I am very thankful for your help!**

**Comment by Jeasmine** [comment]
Hello @suusofttruongnv, unfortunately, if the OS kills the process, there is no way for OneSignal to operate. For example, this is a common behavior of Huawei devices.

Can you please follow the issues template? In that way, we have information about Android versions, % of users affected, the OneSignal version you are using, and seeing this issue. Thanks!

**Comment by jkasten2** [comment]
@suusofttruongnv 

## Issue 1
The issue could either be due to the device delaying the notification or your app being force killed so it will never show. You can try setting a high priority when sending the notification from OneSignal to see if it is a delay issue. Also see this part of the OneSignal documentation to see if your app is being force killed.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#checking-your-app-state

`content_available` only applies to iOS, it doesn't have any effect on Android push notifications.

## Issue 2
Please create a new issue for this one, since it isn't related to first one. Let us know if you are setting a group on your notifications and what devices and Android versions the issue happens on
