### ISSUE TITLE
sendTags issue

### ISSUE THREAD

**Issue by OlegTarashkevich** [OneSignal/OneSignal-Android-SDK#126]
1) Please add ability to append tags. 
Example:

```
OneSignal.sendTag("item", item);
OneSignal.sendTags(jsonObject);
```

sendTags clears previous sendTag.

maybe you can add

```
OneSignal.appendTag("item", item);
OneSignal.appendTags(jsonObject);
```

2) Please add ability to put non String values. You can add String.valueOf() method inside your library. Also Json can contain not only Strings. If I create json object with int and boolean values and then use sendTags is nothing happens. 

I believe that it's easy to implement these 2 features.

**Comment by jkasten2** [comment]
@OlegTarashkevich `sendTag` or `sendTags` always append, the only exception is passing `""` as a value for a key which will delete the key.

We have good test converge around updating tags in our [shouldSendTags](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.3.1/OneSignalSDK/app/src/test/java/com/test/onesignal/MainOneSignalClassRunner.java#L737) method plus a few other tests. Can you share the code you are using to update your tags and how you are verifying the issue.

`booleans` and `integers` should be sent as strings when you add them as tags. See our [testSendTagNonStringValues](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.3.1/OneSignalSDK/app/src/test/java/com/test/onesignal/MainOneSignalClassRunner.java#L845) test. Note arrays and nested objects are not supported by design since the dashboard or the REST API does not support filtering on them.

Thanks.

**Comment by jkasten2** [comment]
@OlegTarashkevich Are you still able to reproduce an issue with your tags being cleared? Could you provide an example project reproduction the issue?

**Comment by OlegTarashkevich** [comment]
@jkasten2 I've updated the onesignal library and seems I can't reproduce it.
Thank you!
