### ISSUE TITLE
Bug GSM Localtion Controller

### ISSUE THREAD

**Issue by mariofelesdossantosjunior** [OneSignal/OneSignal-Android-SDK#1309]
![image](https://user-images.githubusercontent.com/10865241/114716464-74381b80-9d0a-11eb-9fae-c3a2bf64d657.png)

Version One Signal: [4.0.0, 4.99.99]

**Comment by nan-li** [comment]
Hi @mariofelesdossantosjunior, sorry for the delayed response, can you provide more information please.

1. Android versions and device models that are seeing the exception? (other than the one you show above)
2. Percentage of users affected by this crash?
3. Is this crash reproducible?
4. Can you also paste the text instead of an image, so we can copy it.
5. The exact `OneSignal-Android-SDK` version you are using.

**Comment by nan-li** [comment]
Closing due to no response
