### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by M2dL1fe** [OneSignal/OneSignal-Android-SDK#1437]
![image](https://user-images.githubusercontent.com/8074125/133358990-a9588ae8-8785-4a7a-bc5a-e10dc6cb9c9c.png)

4.6.0

**Comment by jkasten2** [comment]
@M2dL1fe Thanks for reporting the crash, with the stack trace. I looked it over and can confirm this was fixed in the 4.5.1 release based on the line numbers in the stack trace.
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.5.1

Please confirm you have updated the version correctly in your `build.gradle` and that the crash wasn't reported from an older version of your app.

**Comment by M2dL1fe** [comment]
@jkasten2 The version I use is 4.6.0
