### ISSUE TITLE
Unable to instantiate service com.onesignal.HmsMessageServiceOneSignal

### ISSUE THREAD

**Issue by justinhandley** [OneSignal/OneSignal-Android-SDK#1507]
**Description:**
This is the same as this ticket which was closed:

https://github.com/OneSignal/OneSignal-Android-SDK/issues/1180

This is on a Samsung galaxy tab, so as per the other, the question is why a Samsung is receiving a message meant only for Huwaii?

#153 java.lang.RuntimeException: Unable to instantiate service com.onesignal.HmsMessageServiceOneSignal: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.HmsMessageServiceOneSignal" on path: DexPathList[[zip file ...

**Environment**

client.android.android_version | 7.1.2
client.android.phone_model | SM-T555

**Steps to Reproduce Issue:**

This is coming from Rollbar on a production react-native app

**Comment by jennantilla** [comment]
Hello @justinhandley apologies that this issue was missed. Since it has been quite some time since you reported this, I will be closing this ticket. In case you missed it, a similar issue was discussed in a separate issue and one of our engineers suggested a workaround [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1262#issuecomment-1067321577). Please @ mention me if you still have questions or concerns.

Also noting that we have an updated major release available for our Android SDK with many improvements and enhancements! Please refer to the [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) for more information on upgrading.

Thanks!

**Comment by justinhandley** [comment]
We upgraded and are no longer facing the issue.
