### ISSUE TITLE
[question]: I'm using one signal android SDK for my android TV app. I'm not able to receive One Signal notification when my app is in background. I only want to get payload, no need to show notification UI. 

### ISSUE THREAD

**Issue by WahajMubeen341** [OneSignal/OneSignal-Android-SDK#1631]
### How can we help?

I understand that there is no notification tray in android TVs which does not affect my use case. I only want to receive a payload via notification within my app even when my app is in the background. Just like in mobile, where even an app in the background still receives notification and displays payload in it's notification tray.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
We do not test our SDK against Android TVs, so I cannot say with confidence what the issue is here. Our documentation for background and data notifications is [here](https://documentation.onesignal.com/docs/data-notifications), just in case some of those steps have not been completed. Have you already implemented the Android [Notification Service Extension](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension)?

**Comment by WahajMubeen341** [comment]
Hi @emawby ! YES i already tried **Notification Service Extension** from the same documentation.  I've been using firebase and onesignal in TV apps for remote notifications but they work while the application is in the foreground. As there is no notification tray for android TV apps, we don't even receive the payload if the app is in the background.
Looking forward to this regard. Thanks

**Comment by WahajMubeen341** [comment]
HI @emawby ! Requestting update on my issue please! Thanks
