### ISSUE TITLE
[Bug]: OSRemoteNotificationReceivedHandler#remoteNotificationReceived called on every app launch

### ISSUE THREAD

**Issue by akushnarev-soul** [OneSignal/OneSignal-Android-SDK#1680]
### What happened?

We have a report from user which receiving the same notification to often. After looking to app logs we see then `OSRemoteNotificationReceivedHandler#remoteNotificationReceived` get called on every app launch.

### Steps to reproduce?

```Markdown
Unknown
```

### What did you expect to happen?

Callback should be triggered once

### OneSignal Android SDK version

com.onesignal:OneSignal:4.8.2

### Android version

11

### Specific Android models

```Markdown
Infinix X695C
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello there! Apologies that this issue was missed. Since it has been some time from the original report, I will be closing this issue. Please @ mention me if we need to revisit.

We have an updated major release available for our Android SDK with many improvements and enhancements! Please refer to the [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) for more information on upgrading.

Thanks!
