### ISSUE TITLE
[question]: Notification Permission fallback dialog language

### ISSUE THREAD

**Issue by ubuntudroid** [OneSignal/OneSignal-Android-SDK#1682]
The `OneSignal.promptForPushNotifications()` function has a `fallbackToSettings` parameter. It looks like the dialog enabled by this parameter is only available in English. 

Is it possible to somehow provide other translations/texts? 

Or at least disable the parameter and decide on our own when to show it? Maybe with some code like this 👇?

```kotlin
OneSignal.promptForPushNotifications(
    false // fallback dialog only supports EN, therefore we handle this manually below
) { isApproved ->
    if (!isApproved) {
        if (!ActivityCompat.shouldShowRequestPermissionRationale(activity, "android.permission.POST_NOTIFICATIONS")) {
            // auto-declined by "never show again" - route to settings instead
            NavigateToAndroidSettingsForNotifications.show(activity)
        } else {
            // declined by user interaction in permission dialog
        }
    }
}
```

Or am I missing something?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ubuntudroid** [comment]
Ah, dang, with that workaround code I would also have to mimic the `awaitingForReturnFromSystemSettings` from `NotificationPermissionController`.

**Comment by jkasten2** [comment]
@ubuntudroid Thanks for question. The `NavigateToAndroidSettingsForNotifications` class wasn't indented to be used by outside the SDK, this means behavior or name could change in any release.

Since you are looking to change just the text for the prompt I recommend defining your own string sources keys as listed here in your app project:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.8.2/OneSignalSDK/onesignal/src/main/res/values/strings.xml

Defining the same names with different language folders should allow the SDK to pick it up. Let us know if this doesn't work for you.

**Comment by ubuntudroid** [comment]
That's a great hint, thanks for the quick heads-up @jkasten2 ! I'll test that and let you know.

**Comment by ubuntudroid** [comment]
@jkasten2 works perfectly fine! 👍

**Comment by ubuntudroid** [comment]
I guess the only downside is, that we wouldn't even notice in case those strings keys would change in future SDK versions or if they wouldn't be used anymore in the dialog. 🤔

**Comment by jkasten2** [comment]
@ubuntudroid I can say those are safe for any 4.x.x version of this SDK. There is always a possibility any public API on a major release (example 5.0.0) it could change, however we will document that in the release notes and migration guide.

**Comment by ubuntudroid** [comment]
Sounds great, thanks again! 🙏
