### ISSUE TITLE
Activity / app not launching in foreground with custom notificationOpened

### ISSUE THREAD

**Issue by opheliadesign** [OneSignal/OneSignal-Android-SDK#169]
I am switching from Parse to OneSignal. On Parse, I had a BroadcastReceiver that generated a notification and set a `PendingIntent` to launch an activity when the notification was clicked. I am trying to replicate this with OneSignal.

When the app is running in the background, everything works as would be expected - you click on the notification and the app comes to the foreground with that activity / data. However, if the app is not running, nothing happens when you click on the notification. When the app is launched again, the `Intent` fires and the correct activity is displayed.

MainActivity onCreate:
```
// Init OneSignal
OneSignal.startInit(this).setNotificationOpenedHandler(new NotificationOpenHandler()).init();
```

```
class NotificationOpenHandler implements OneSignal.NotificationOpenedHandler {
        // This fires when a notification is opened by tapping on it.
        @Override
        public void notificationOpened(OSNotificationOpenResult result) {
            JSONObject data = result.notification.payload.additionalData;

            String stationName = data.optString("stationName");
            String timestamp = data.optString("timestamp");
            String filename = data.optString("filename");
            String url = getString(R.string.callResourceUrl) + filename;

            Log.d("APP", "Notification clicked");

            Intent intent = new Intent(getApplicationContext(), CallActivity.class);
            intent.putExtra("stationName", stationName);
            intent.putExtra("time", timestamp);
            intent.putExtra("url", url);
            intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT | Intent.FLAG_ACTIVITY_NEW_TASK);
            startActivity(intent);
        }
    }
```
What am I doing wrong here?

**Comment by jkasten2** [comment]
@opheliadesign Are you seeing your `"Notification clicked"` entry in the log to confirm that the `notificationOpened` method is firing?

Since you are displaying your own `Activity` from `onCreate` of your `Application` class did you disable our automatic opening the the launcher `Activity` with the following line in your `AndroidManifest.xml`?
```XML
<application ...>
   <meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />
</application>
```

See the link below for more details on this.
https://documentation.onesignal.com/docs/android-customizations#section-changing-the-open-action-of-a-notification

Thanks.

**Comment by opheliadesign** [comment]
I will check again tomorrow but if I recall correctly the log entry never displays. Android Manifest is set correctly. When you click the notification, it disappears and that's all.

Parse clearly demonstrated how to receive a push, create a custom notification with a Pending Intent, and register a Broadcast Receiver. I cannot seem to find anything in the OneSignal documentation along these lines - namely, having a registered Broadcast Receiver and launching a Pending Intent.

**Comment by jkasten2** [comment]
@opheliadesign We do have the same capabilities, however you will have to change a few things as our SDK relay more off callback instead of `Intents`.

If you need to do something custom when a notification is received I recommend checking out the guide below.
https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding

You noted in your original post that you added `OneSignal.startInit...` to your `Activity`. If you need to control which `Activity` is launched from a notification you will need to move this to your `Application` class instead.

**Comment by opheliadesign** [comment]
@jkasten2 Oh geez, you can tell it's been a minute since I coded in Java / Android. Checked my old Parse configuration, guess what? It is initialized in a class that extends Application. 

Rookie mistake, everything is working beautifully now. It would be nice to have a note about this in the docs for busy / noob Android developers.

Thanks so much for providing this service for free!

**Comment by Behtom** [comment]
Hi @opheliadesign! I read your post and I have the same issue in my app. I already encoded my ExtenderService class with PendingIntents but does not work. Could you help me to solve it please?
