### ISSUE TITLE
[question]: Adding OneSignal dependency causing Activity Reload on Android 13

### ISSUE THREAD

**Issue by themeink** [OneSignal/OneSignal-Android-SDK#1703]
### How can we help?

I have implemented OneSignal in my app which is causing the Launch Activity to reload on the very first App Launch. I even removed the OneSignal initialization code and found out that just adding the OneSignal dependency in app's build.gradle is causing the issue. The weird thing is that it happens on the very first app launch and not on subsequent launches.

On investigation, I found out that some Configuration change is happening which is causing the activity to reload. By Overriding OnPause method of apps Launch Activity and calling getChangingConfigurations(); I got the int value of the config that has changed to -2147483648 . On further investigation, I found out that the said constant value relates to SIGNAL_STRENGTH_UNSPECIFIED which can be found out [HERE](https://developer.android.com/reference/android/net/NetworkCapabilities#SIGNAL_STRENGTH_UNSPECIFIED) . Now I am out of ideas how to fix it. Any help is appreciated. TIA

Here is the complete Log

[LOG](https://hastebin.com/osefigixun.apache)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @themeink apologies that this issue was missed. Since it has been quite some time since you reported this, I will be closing this ticket. Please @ mention me if you still have questions or concerns.

Also noting that we have an updated major release available for our Android SDK with many improvements and enhancements! Please refer to the [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) for more information on upgrading.

Thanks!
