### ISSUE TITLE
 releasequestion]:  'OSNotificationOpenedResult' and 'OSNotificationOpenedHandler' removed from 4.8.4 release 

### ISSUE THREAD

**Issue by deeteeh** [OneSignal/OneSignal-Android-SDK#1715]
Cannot resolve symbol 'OSNotificationOpenedResult'
Cannot resolve symbol 'OSNotificationOpenedHandler'

Is this intentionally done? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @deeteeh this was not intentional, and I believe they are still there:

[OSNotificationOpenedResult](https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.8.4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenedResult.java#L40)
[OSNotificationOpenedHandler](https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.8.4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L178)

I don't believe anything significant has changed recently relating to our build/linking process. Which release did you upgrade from?

**Comment by jennantilla** [comment]
Closing due to no response.

@deeteeh feel free to reach out if you are still having issues. 

We have also released a new major version of OneSignal with many improvements and enhancements. Check it out [here](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.2). The [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) will have updated information on handling notification clicks on the newest version.

Thanks!
