### ISSUE TITLE
[question]: How to clear all data tags in 5.0.0?

### ISSUE THREAD

**Issue by Popda** [OneSignal/OneSignal-Android-SDK#1805]
### How can we help?

In 5.0.0 version we have functions to remove tags by name but how should they be managed in case if current tags for user are unknown? In 4.x.x version we could check existing tags with getTags() fun  to get names of tags and manage them as we like but it was removed in 5.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@Popda With the 5.0.0 SDK you can simply add the tags each time in yoru app. The SDK is optimized to only send what is out of sync to OneSignal.

Or by "manage them" is it a must to be able to read them? If so can you give an example?

**Comment by Popda** [comment]
@jkasten2 tags are set or removed for the user based on his interactions with the app so at some point he may loose some tags but our server gives us only list of tags that user should have and without getTags()  we dont know what tags we should remove.
If we had a way to clear tags for the user, we could remove them all and set tags sent by our server

**Comment by jennantilla** [comment]
@Popda thanks for your patience! We do have the method [`removeTags`](https://documentation.onesignal.com/docs/data-tag-implementation#removing-multiple-tags-at-once) which would allow you to provide an array of all tag keys you wish to remove from the user. So as long as you track whatever tags you add, you could use this method. Would that work for your purposes?

**Comment by Popda** [comment]
> @Popda thanks for your patience! We do have the method [`removeTags`](https://documentation.onesignal.com/docs/data-tag-implementation#removing-multiple-tags-at-once) which would allow you to provide an array of all tag keys you wish to remove from the user. So as long as you track whatever tags you add, you could use this method. Would that work for your purposes?

Hi, what if I don't track tags added and don't have list of tags to remove?
In our case we don't track tags added, we just get list of tags we should have from our server so in 4.8.6 we were checking present tegs with getTags function and then removing or adding tags to match our list of tags but in 5.0.0 getTags is not available

**Comment by jennantilla** [comment]
Hi @Popda just wanted to circle back on this. 

Currently, there is no SDK method in our 5.0.0 major release to retrieve all stored tags. Accessing this data via the SDK is beyond the intention for data tags, which is purely for messaging purposes.

If you wish to access all the existing tags for your users, you could consider using our CSV exporter so that you can begin tracking tag keys. Similarly, you could bulk-edit tags via [CSV import](https://documentation.onesignal.com/docs/import-user-tags#editing-and-deleting-your-data-tags) if you wish to delete all data tags.

I will pass your feedback along to our Product team so that a method similar to `getTags` may be considered for future development.

Please let us know if you have any additional questions or concerns!
