### ISSUE TITLE
Conflicting idsAvailable calls

### ISSUE THREAD

**Issue by lukyanov** [OneSignal/OneSignal-Android-SDK#181]
Hello,

When a user has purchases, you send them to OneSignal in your own idsAvailable callback:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/82900a23124cc6d76a52f1f8b044f286b69a855d/OneSignalSDK/onesignal/src/main/java/com/onesignal/TrackGooglePurchase.java#L229

The thing is that when I set up my own idsAvailable callback it seems to interfere with yours. More precisely, depending on some conditions when the application is starting, there seems to be a race condition on setting the callbacks. My own callback may be rewritten by yours. It is usually happens when starting the app for the first time.

The workflow looks like this:
1) OneSignal SDK starts the initialization process.
2) My idsAvailable callback gets called (no ids available yet, as the initialization process is in progress).
3) OneSignal SDK sets its own callback when sending purchases.
4) ids are ready
5) Your internal callback is called, mine is not (as it was rewritten in step 3), and I never receive ids.

Is this something that can really take place or am I just misunderstanding the workflow? What would you recommend in this case?

**Comment by jkasten2** [comment]
@lukyanov Thanks for investigating, this is race condition that can be hit on the first start of the app. Once we have an user / player id and registration id from Google future calls won't have an issue. This is because it will fire without a delay after this.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.4.3/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L864-L869
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.4.3/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L894

I'll look into fixing this in our next release.

Thanks.
