### ISSUE TITLE
Is it okay to initialize OneSignal only before login or when user is already logged in?

### ISSUE THREAD

**Issue by ilhomsoliev** [OneSignal/OneSignal-Android-SDK#1975]
### How can we help?

I don't want guests to be in the OneSignal dashboard, and I thought if I call 'OneSignal.initWithContext(context, ONESIGNAL_APP_ID)' only when login or when user is already is logged in, is that okay? Or it is not recommended? What is the problems with doing so?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@ilhomsoliev Unfortunately right now there is not a great way to prevent guest users from being created on initialize like you want. We recommend initializing OneSignal before login. 

We are working on new methods for the SDK that will allow you to prevent creating guest users at all (you will need to Login in order to have a user), but they are not yet available.
