### ISSUE TITLE
[Bug]: Operation is not permitted due to user having the maximum number of subscriptions assigned

### ISSUE THREAD

**Issue by fury21** [OneSignal/OneSignal-Android-SDK#2005]
### What happened?

When i start my app, i got an error in console: ERROR: OSUserExecutor create user request failed with error: Optional(Error Domain=OneSignalError Code=409 "(null)" UserInfo={returned={
    errors =     (
                {
            code = "subscription-1";
            meta =             {
                "user_subscription_limit" = 20;
            };
            title = "Operation is not permitted due to user having the maximum number of subscriptions assigned";
        }
    );
    httpStatusCode = 409;
}})

SDK 5.1.0
iOS simulator 17.2

Whats mean the error test? How can i resolve this error?

### Steps to reproduce?

```Markdown
Every time i started the app
```

### What did you expect to happen?

No error

### OneSignal Android SDK version

5.1.0

### Android version

13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @fury21 thanks for your patience!

This error is due to the user having too many subscriptions. Is this a test user? If so, you can log out of this user and log in to another user with fewer subscriptions. Or, you can clean up unnecessary subscriptions for the user. See our [documentation](https://documentation.onesignal.com/docs/delete-users) for further details. Please let us know if you have any additional questions or concerns!

**Comment by petodavid** [comment]
Deleting subscriptions by hand is not an option in a large app with lots of users. Considering that having more than 20 subscriptions for a user is not impossible in the long run, I would like to ask what the best practice is for managing this? Are you planning to improve this?

**Comment by jkasten2** [comment]
@fury21 @petodavid there is a recommendation here and a note of an SDK issue not handling the error in this comment:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/2143#issuecomment-2218710776

Please follow that issue for updates.
