### ISSUE TITLE
Package manager has died

### ISSUE THREAD

**Issue by OlegTarashkevich** [OneSignal/OneSignal-Android-SDK#224]
@jkasten2 Please look at the attached screenshot. 

v.3.5.4

![screen shot 2017-05-05 at 09 55 16](https://cloud.githubusercontent.com/assets/13828110/25736681/1fd36494-317c-11e7-9113-09551de65095.png)

**Comment by jkasten2** [comment]
@OlegTarashkevich Thanks for the log. It seems like this crash came from our 3.4.4 SDK. The [`DeadObjectException`](https://developer.android.com/reference/android/os/DeadObjectException.html) seems like it would be externally rare and would only happen if some Android system process died.

Are you able to reproduce this on your test devices?

**Comment by OlegTarashkevich** [comment]
@jkasten2 Thank you for your response. It happened on my last app build (only once), that published on the google play. I used 3.5.4. I can't reproduce it, on my side all works properly.

**Comment by OlegTarashkevich** [comment]
@jkasten2 The same crash happened on my another project with OneSignal v.3.5.3
![2017-05-11 20 55 37](https://cloud.githubusercontent.com/assets/13828110/25964075/4a4ea78c-368c-11e7-9f3d-441499c82f1c.png)

**Comment by jkasten2** [comment]
We haven't received any recent reports of this. Let us know if you are still seeing it and how many cases and we can investigate more accordingly. Thanks!

**Comment by kerimovscreations** [comment]
![image](https://user-images.githubusercontent.com/10672530/41742857-52e6d0c2-75b0-11e8-8377-2c8287a2cbe0.png)
This issue has occurred in my application.

**Comment by jkasten2** [comment]
@kerimovscreations Thanks for reporting. I have seen more than on instance of this crash? Are you able to reproduce this crash?

This is most likely related to the Android Core itself crashing and throwing this exception. More details to the similar issue #567

**Comment by shefich** [comment]
Also happens in my project.

Stacktrace:
`Fatal Exception: java.lang.RuntimeException
Package manager has died
android.app.ApplicationPackageManager.getPackageInfo (ApplicationPackageManager.java:134)
com.onesignal.OneSignal.registerUserTask (OneSignal.java:1521)
com.onesignal.OneSignal.access$1500 (OneSignal.java:86)
com.onesignal.OneSignal$10.run (OneSignal.java:1495)
java.lang.Thread.run (Thread.java:818)

Caused by android.os.DeadObjectException
android.os.BinderProxy.transactNative (Binder.java)
android.os.BinderProxy.transact (Binder.java:503)
android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo (IPackageManager.java:2163)
android.app.ApplicationPackageManager.getPackageInfo (ApplicationPackageManager.java:129)
com.onesignal.OneSignal.registerUserTask (OneSignal.java:1521)
com.onesignal.OneSignal.access$1500 (OneSignal.java:86)
com.onesignal.OneSignal$10.run (OneSignal.java:1495)
java.lang.Thread.run (Thread.java:818)`

Unity 2021.3.23
OneSignal 3.0.10
