### ISSUE TITLE
all com.android.support libraries must use exact same

### ISSUE THREAD

**Issue by karopass** [OneSignal/OneSignal-Android-SDK#238]
Hi !
I am trying to integrate onesignal in one of my android application.
I am using com.android.support:support-v4:25.3.1 in my Gradle file and after complie onesignal library...its giving me above error....I should Downgrade my support library for complie onesignal ?
Thanks

**Comment by jkasten2** [comment]
@karopass You can add the following to your `build.gradle` to resolve the version conflict.
```
compile 'com.android.support:customtabs:25.3.1'
```

Please list the full gradle error you are getting if the above doesn't fix the issue.

**Comment by karopass** [comment]
![newee](https://cloud.githubusercontent.com/assets/18382500/26615797/3e01343a-45e7-11e7-82ab-fc56b1f28748.png)
Now I am getting error like this

**Comment by jkasten2** [comment]
@karopass You can add the following to update the other part of the `gms` library that it is noting is a mismatched version.
```Gradle
 compile 'com.google.android.gms:play-services-location:10.2.6'
```

**Comment by 2x2xplz** [comment]
I don't think the correct solution is for developers to have to keep track of extra dependencies. It appears your library statically links to older versions of the support and Play Services libraries, which probably wasn't noticed previously because Android Studio didn't raise any warnings until version 2.3+

I ran `./gradlew -q dependencies myappnamehere:dependencies --configuration compile` and got this output:
![onesignal](https://user-images.githubusercontent.com/16587079/29009345-5b460bcc-7ad7-11e7-8b65-e27a14982365.png)

I believe my project uses v.26.0.0 and 11.0.4 of the other libraries because I am already explicitly referencing them in my build.gradle. But if I am using a recent version of OneSignal, the library should automatically reference more recent library versions.
