### ISSUE TITLE
Launch intent before calling callback

### ISSUE THREAD

**Issue by glat** [OneSignal/OneSignal-Android-SDK#251]
First, I use this SDK by using the Xamarin SDK. I noticed that in this case:
1. launchUrl empty
2. notificationOpenedDelegate used (in Xamarin SDK)
3. App is fully closed

When the App gets a notification first the delegate is called and later the App is started causing the impossibility to get any other data about the notification.

I checked source code and I think that in this function:

public static void handleNotificationOpen(Context inContext, JSONArray data, boolean fromAlert)

runNotificationOpenedCallback and latest if should be inverted, so to start App before to callback.

**Comment by jkasten2** [comment]
@glat I reviewed the `handleNotificationOpen` in the SDK and both cold starts and resumes are handled correctly by it. The order of running `runNotificationOpenedCallback` then `fireIntentFromNotificationOpen` is intentional.

`runNotificationOpenedCallback` will store the the notification data in `unprocessedOpenedNotifis` if the the app didn't have time to setup a open handler yet. Then once the app calls `OneSignal.startInit().setNotificationOpenedHandler(...).init()` any saved open events will be fired to the open handler that was passed in.

The issue you are seeing would seem to be an issue with the Xamarin SDK along with the way you are initializing it there. Can you open an issue on the Xamarin OneSignal SDK repo sharing your init code as well as the method it is being called from?

**Comment by glat** [comment]
I  know nothing about java and android but I can assure that notification handler in Xamarin SDK is called every time BEFORE app is started, and this is not the correct behaviour.
I'll open an issue on Xamarin SDK github project, but I think the real matter is in the Android SDK.
Thanks
