### ISSUE TITLE
Option to change the string for close button when using EnableInAppAlertNotification

### ISSUE THREAD

**Issue by VSG24** [OneSignal/OneSignal-Android-SDK#26]
Currently the value is hard coded in Java and there's no way for us to change it using the api. That makes it impossible to localize. Please add an option to change that string in client side.

**Comment by jkasten2** [comment]
We are considering localizing this button in our SDK instead of adding an API parameter for it. You can use one of the following options in the meantime however.
* Set call `OneSiganl.enableNotificationsWhenActive(true);` after OneSignal init.
* In your `NotificationOpenedHandler` use `AlertDialog` to display your own alert.

Thanks.

**Comment by VSG24** [comment]
Thanks for considering that but I still think it's best if you provide an API parameter for it. In case we need to override it.

**Comment by jkasten2** [comment]
@VSG24 In our SDK 3.0 you can now set a string for the key `onesignal_in_app_alert_ok_button_text` in your `string.xml` to override the button text.
