### ISSUE TITLE
Silent notification broken on android

### ISSUE THREAD

**Issue by Thaina** [OneSignal/OneSignal-Android-SDK#301]
From this issue I got in unity https://github.com/OneSignal/OneSignal-Unity-SDK/issues/64

I found a bug in android sdk at NotificationBundleProcessor.java:166

https://github.com/OneSignal/OneSignal-Android-SDK/commit/75e7c333bf4d3908ba6cc0381fc7e44ab157ea9a#commitcomment-24425047

**Comment by jkasten2** [comment]
@Thaina The silent / blank body notification issue was introduced in version 3.6.0 of this SDK but was fixed in [version 3.6.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.6.2). Closing this issue as this bug has been fixed.

The Unity SDK is still using 3.6.0, I'll leave that Unity issue open so the update can can tracked there.
