### ISSUE TITLE
Excessive wakeups

### ISSUE THREAD

**Issue by baole** [OneSignal/OneSignal-Android-SDK#325]
Google Play reports "experienced excessive wakeups" caused by OneSignal

![image](https://user-images.githubusercontent.com/1460168/31218887-f24999ea-a9bb-11e7-94b8-57aefcb89c45.png)
![image](https://user-images.githubusercontent.com/1460168/31220371-8612f488-a9c0-11e7-8e71-02de908cc541.png)

Why does OneSignal need so many acquire many wakelock?

**Comment by Alamgir** [comment]
@baole OneSignal conducts a "wakeup" in order to determine if any tags/state needs to be synced. This occurs every 10 mins if the app is backgrounded in order to update statistics like location. On Android 8.0 Oreo, this syncing was moved to a JobScheduler which is compliant with Google's policies regarding background processing.

**Comment by baole** [comment]
Thanks @Alamgir, in our use case, we don't use (need) location and tags syncing is not critical. We also don't want our app to run in the background which consumes device's battery and bandwidth. 

Is there anyway to change this behaviour? Such as app syncs tags only when app is in foreground?

**Comment by Alamgir** [comment]
@baole there currently is no developer-facing way to "throttle" or prevent OneSignal sync operations - we're very careful about how we schedule alarms and jobs to be battery and network efficient.
