### ISSUE TITLE
RegistrationId can be null, it should be marked as `@Nullable` in the API.

### ISSUE THREAD

**Issue by runningcode** [OneSignal/OneSignal-Android-SDK#348]
```
public interface IdsAvailableHandler {
  void idsAvailable(String userId, String registrationId);
}
```
The registrationId can be null when the callback is fired.

For example, in `OneSignal#internalFireIdsAvailableCallback()`:

```
String regId = OneSignalStateSynchronizer.getRegistrationId();
if (!OneSignalStateSynchronizer.getSubscribed())
   regId = null;
```

**Comment by runningcode** [comment]
It would also be nice to understand why this field is null and what it means.

**Comment by jkasten2** [comment]
@runningcode There is now a [`getPermissionSubscriptionState`](https://documentation.onesignal.com/docs/android-native-sdk#section--getpermissionsubscriptionstate-) that reports more details on what the status of the subscription is. Let me know if this doesn't cover what you need

Also [`addPermissionObserver`](https://documentation.onesignal.com/docs/android-native-sdk#section--addpermissionobserver-) and [`addSubscriptionObserver`](https://documentation.onesignal.com/docs/android-native-sdk#section--addsubscriptionobserver-) that provides this same detail when ever these properties change.

**Comment by jkasten2** [comment]
@runningcode `idsAvailable` will be marked deprecated and has been removed from the OneSignal API docs since these new methods provide more details.

`idsAvailable` gives a `null` `registrationId` if you have called `setSubscription` with `false` or if the user has turned of notifications for your app. In addition the `idsAvailable` would not fire at all until the device registers with OneSignal. These new APIs has been decoupled from these statuses so `registrationId` is set if the device was successful in registering with Google. `OSSubscriptionState` includes a `getSubscribed()` method to know if the user can receive OneSignal push notifications. `OSPermissionState` contains the `setSubscription` state that can be read from `getUserSubscriptionSetting`. `OSSubscriptionState` contains `getEnabled()` to know if the user has disabled notifications.

The OneSignal SDK will retry if there was an error from Google getting `registrationId` so you don't have to handle this yourself. Is there any specific use cases or more details you need to present to your users?

**Comment by runningcode** [comment]
@jkasten2 Is there some documentation on what the fields `from` and `to` mean in  `OSSubscriptionStateChanges`? What do they mean and how should they be used?

What does the `pushToken` field in `OSSSubscriptionState` mean?
What happens when I call the `setPushToken()` method on `OSSubscriptionState` object?

How can I retrieve the `registrationId` with the new APIs you described?

**Comment by runningcode** [comment]
It seems that `pushToken` is the replacement for `registrationId`? is that correct? I don't see this in the docs. Are there any differences in terms of how it should be used? Are they backwards compatible?

**Comment by jkasten2** [comment]
@runningcode Good questions!, we will update our docs with these details. I'll let you know when they are available

**Comment by runningcode** [comment]
Also in testing out the new api I find that the userId is null when the pushToken is not null. What does this mean?

**Comment by runningcode** [comment]
Would it be possible to mark those fields as nullable and document them in the SDK? I find it a lot quicker to look at the documentation for the code I'm looking at instead of having to search somewhere else for documentation.

Also, how can we force onesignal to register for this case so that it isn't null?
> The OneSignal player / user id for the device. null if the device hasn't registered with OneSignal's server yet.

**Comment by jkasten2** [comment]
@runningcode For the nullable annotation we are going to wait until a 4.0.0 release of this SDK. We don't want to break anyone's project with unexpectedly.

The SDK retries automatically to register the device. The player / user id will only stay `null` if there was a networking issue to onesignal.com.

**Comment by runningcode** [comment]
We'll begin exploring more reliable alternatives to onesignal in our next roadmap.

**Comment by jkasten2** [comment]
@runningcode In the [OneSignal 3.9.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.9.0) we changed to use FCM instead of the GCM library to register the device. This is a fairly large change but we haven't seen a drop in registrations. Can you contact OneSignal support from the dashboard or create new ticket here on this repo with more details so we can help produce this issue?

**Comment by vlad-roid** [comment]
For me it was the other way round: using GCM lead to lots of unsubscribed devices, and switching to FCM solved it. Although for some reason GCM would always work when testing on a debug build, and when testing on a release build my device would never subscribe ...

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
