### ISSUE TITLE
DexOpt: access denied from Lcom/onesignal/GenerateNotification;

### ISSUE THREAD

**Issue by kafabih4raka** [OneSignal/OneSignal-Android-SDK#363]
Hello, I have found another bug here, can you explain why? as is shown on my logcat down here

dalvikvm: DexOpt: access denied from Lcom/onesignal/GenerateNotification; to field Landroid/support/v4/app/NotificationCompat$Builder;.mNotification

I use the android:permission="android.permission.BIND_JOB_SERVICE" like you said in the changelogs, but it didn't work.

**Comment by jkasten2** [comment]
@kafabih4raka This is due to an incompatibility with the OneSignal SDK and the Android Support library revision 27+. Until the OneSignal SDK is updated you will need to continue using 26.X instead.

You can follow the issue below for updates for a release.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/363
