### ISSUE TITLE
New Location APIs

### ISSUE THREAD

**Issue by valentinmoscone** [OneSignal/OneSignal-Android-SDK#377]
Hello,

I am having a problem while trying to add the new location API (FusedLocationProviderClient) to my project. For some reason the app stopped receiving push notification when the app is closed (not running). 

 - 'com.google.android.gms:play-services-location:11.2.2'

Example:

    compile ('com.onesignal:OneSignal:3.6.5') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'customtabs'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }

If i do not exclude the libraries i get:

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:design:26.0.1] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

I'm using buildToolsVersion "26.0.1" (support library, app-compat, etc)

There's no stack trace in Android Monitor. So is a bit difficult to find the library issue. Thanks for the help!

**Comment by jkasten2** [comment]
@valentinmoscone OneSignal 3.6.5 uses the Android Support library revision 26.1.0. However some other dependencies are using 26.0.1 instead which is creating the merge issue you noted above.

Using `exclude` on `compile ('com.onesignal:OneSignal:3.6.5')` will fix the build error however it will be missing those decencies  at runtime which will cause OneSignal not to work. Based on your exclude list you will need to make sure you have `com.android.support:support-v4` in your list. 

However instead of resolving these dependencies manually I recommend adding the [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) which auto resolves these conflicts for you. You will then also need to remove your ` exclude group:` lines.

If notifications are working in the foreground then the issue most likely isn't a dependency issue. If you're still seeing a background issue I recommend checking the logcat for any errors or warnings.

**Comment by jkasten2** [comment]
@valentinmoscone Feel free to open an issue on the [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) if you are still seeing this issue after adding the gradle plugin.

**Comment by valentinmoscone** [comment]
@jkasten2 Thanks for a lot for the help!!! I added the [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) and is working as expected. I let you know if i have any problem with the plugin.
