### ISSUE TITLE
wrong pom description at maven central (perhaps)

### ISSUE THREAD

**Issue by escalope** [OneSignal/OneSignal-Android-SDK#404]
Hi
I think your pom description as uploaded to maven central is wrong. It works with gradle, but when trying the maven-android-plugin, missing artifact errors are triggered.  Now that google repositories are available for maven when adding this to the pom.
    <repository>
      <id>googlemaven</id>
      <name>google</name>
      <url>http://maven.google.com</url>
    </repository>

It makes sense for maven people to keep using a pure maven based approach for android apps construction. However, it fails because of the problem I mentioned.

I traced back the problem to the dependency declaration of onesignal at maven central. Check for instance:
- https://search.maven.org/remotecontent?filepath=com/onesignal/OneSignal/3.7.1/OneSignal-3.7.1.pom
- https://search.maven.org/remotecontent?filepath=com/onesignal/OneSignal/3.7.0/OneSignal-3.7.0.pom
- ...
- https://search.maven.org/remotecontent?filepath=com/onesignal/OneSignal/3.5.3/OneSignal-3.5.3.pom

The dependency with respect other artifacts follows this structure in abovementioned poms

    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-gcm</artifactId>
      <version>[10.2.1, 11.7.0)</version>
      <scope>compile</scope>
    </dependency>

But now it should be
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-gcm</artifactId>
      <version>[10.2.1, 11.7.0)</version>
      <scope>compile</scope>
	<type>aar</type>
    </dependency>

The AAR part is important to tell maven that aar files and not jar files are to be used. I made by hand this change and compilation works, where before there were missing artifacts errors.

**Comment by jkasten2** [comment]
@escalope Thanks for reporting. I just created a SNAPSHOT build so you can try the fix for this.
1. Add the following snapshot repo if you don't have it already.
`https://oss.sonatype.org/content/repositories/snapshots`
2. Add the following specific version with this fix.
`com.onesignal:OneSignal:4.0.0-20180112.003255-6`

I haven't tested `maven-android-plugin` but for reference this is how it would look in gradle.
```gradle
repositories {
  maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}
dependencies {
    compile 'com.onesignal:OneSignal:4.0.0-20180112.003255-6'
}
```

Direct link to the new POM file.
https://oss.sonatype.org/content/repositories/snapshots/com/onesignal/OneSignal/4.0.0-SNAPSHOT/OneSignal-4.0.0-20180112.003255-6.pom

Let me know if this for you.

**Comment by jkasten2** [comment]
@escalope Let us know if the above snapshot works for you. If so we can merge this in to our future builds. Thanks
