### ISSUE TITLE
App crashes after push notifications possible initiator getColor

### ISSUE THREAD

**Issue by canado** [OneSignal/OneSignal-Android-SDK#410]
Hi Onesignal team

I received a lot of crashes errors after a push notification, here is the details I have in Firebase.

Is there restricted colors we should not use  ?
getColor seems to be the error here.

Thanks

> android.content.res.ResourcesImpl.getValue (ResourcesImpl.java:190)
> android.content.res.Resources.getColor (Resources.java:922)
> org.apache.cordova.firebase.FirebasePluginMessagingService.sendNotification (FirebasePluginMessagingService.java:105)
> org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived (FirebasePluginMessagingService.java:71)
> com.google.firebase.messaging.FirebaseMessagingService.handleIntent ()
> com.google.firebase.iid.zzc.run ()
> java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
> java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
> java.lang.Thread.run (Thread.java:761)

**Comment by canado** [comment]
My custom colors for LED includes

blue = "FF0000FF";
orange ="FFFF8800";
green ="FF00ff00";
yellow ="FFFFFF00";

**Comment by jkasten2** [comment]
@canado  This crash is coming from `cordova-plugin-firebase` in your project. From looking at their source the issue is happening at:
https://github.com/arnesson/cordova-plugin-firebase/blob/550798c1d62f40a1c376b7eb14dd12453779c0df/src/android/FirebasePluginMessagingService.java#L105

This isn't need for OneSignal so you can remove or disable the push notification part if you don't need it.

There is an open issue on their repo and many others have run into their issue
https://github.com/arnesson/cordova-plugin-firebase/issues/270

**Comment by canado** [comment]
Hi Josh,

Thank you for pointing me to the right direction, I believed it was coming from the firebase console.log equivalent for crash stats.

I use firebase in my project but not firebase cloud messaging. I only trigger onesignal when I have an alert to push on my users's screen.
I will look into firebase 

Thank you so much
