### ISSUE TITLE
Updating plugin from 0.7.0 to 0.8.1 result in build failure

### ISSUE THREAD

**Issue by niqo01** [OneSignal/OneSignal-Android-SDK#413]
After upgrading onesignal plugin from 0.7.0 to 0.8.1 I get:
```
Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:prePlayDevDebugBuild'.
> Android dependency 'com.google.firebase:firebase-core' has different version for the compile (11.6.2) and runtime (11.4.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

Rolling back to 0.7.0 solve the issue.

I was wondering why Onesignal plugin need to manipulate dependencies ?

**Comment by jkasten2** [comment]
@niqo01 Thanks for the report. This seems very similar to the issue below but since it is on `firebase-core` instead of `onesignal` it might be getting triggered a bit differently.
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/16

Do you have different `targetSdkVersion` in your `build.gradle` for your `productFlavors` or `buildTypes`? If so this could be causing different dependences to be set as each task is processed. If possible could you add your `app/build.gradle` and your root `build.gradle` to the issue above?

The [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) was created to ensure a compatible versions of the OneSignal SDK and it's dependencies are used in the APK. Mostly around making sure compatible versions of Google Play services and the Android Support library are used. Gradle is missing dependency defined group version alignment to do this automatically. Google's Gradle plugin also is missing both `targetSdkVersion` and `compileSdkVersion` check for their own libraries which this provides. More details in the links below.
* [OneSignal-Gradle-Plugin Readme](https://github.com/OneSignal/OneSignal-Gradle-Plugin)
* Issue https://github.com/OneSignal/OneSignal-Android-SDK/issues/303, some initial discussion

**Comment by jkasten2** [comment]
@niqo01 Moving this issue to OneSignal/OneSignal-Gradle-Plugin#16 since the error is related to the gradle plugin project. Please follow up there if you are still seeing this issue. Thanks
