### ISSUE TITLE
NPE in  OneSignalStateSynchronizer.java line 236

### ISSUE THREAD

**Issue by paularius** [OneSignal/OneSignal-Android-SDK#434]
I'm getting a crashlytics error, that looks like this: 
![image](https://user-images.githubusercontent.com/1263573/35917511-124c5742-0c17-11e8-9cfe-c8b440649b9a.png)

The thing is that I cannot reproduce it, so any ideas?
I am using the 3.7.1 of the SDK.

**Comment by jkasten2** [comment]
Thanks for the report, we will look into reproducing the issue.

**Comment by jkasten2** [comment]
@paularius After reviewing the code in the 3.7.1 release this could happen in a rare case when initializing OneSignal in an Activity instead of in the onCreate of your Application class.  I have made some large change to the SyncService in the #470 PR which will end up solving this `null` error as well.

It will included in the 3.8.2 update this week, feel free to reply if this doesn't solve the issue after updating. Thanks!
