### ISSUE TITLE
Google removing GCM in favor of FCM

### ISSUE THREAD

**Issue by summera** [OneSignal/OneSignal-Android-SDK#507]
I received an email saying GCM will no longer work after **April 11, 2019** so apps need to be upgraded to FCM before then. I see that this library uses/depends on GCM. In the [docs](https://documentation.onesignal.com/docs/firebase-cloud-messaging-fcm) it says that it can work with FCM. 

- Do you have docs for how to migrate to FCM using OneSignal? 
- And do you plan to upgrade this library soon to depend on FCM?

**Comment by jkasten2** [comment]
@summera Making sure your app in on the Firebase console is one part of the depreciation Google noted in their email. You can import your Google Project into Firebase from the Firebase console if you haven't done so already. This should be done instead of creating a new Firebase app to keep your subscribers. We will be providing exact details on this soon.

The 2nd part is this SDK depending on the GCM library. This is part of the Google Play services library `com.google.android.gms:play-services-gcm` and it will be remove from future versions of the Google library come April 11, 2019. We will be updating our SDK over the next few weeks to support FCM so you can start this part of the required migration soon.

**Comment by jkasten2** [comment]
@summera @rameshvoltella We just released [version 3.9.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.9.0) that supports FCM. GCM will be drop and FCM will be added with the upgrade automaticly as long as you followed the [OneSignal standard setup guide](https://documentation.onesignal.com/docs/android-sdk-setup#section-1-gradle-setup).

**Comment by summera** [comment]
@jkasten2 Thanks a lot! I'll be upgrading the SDK soon.
