### ISSUE TITLE
OTHER Apns 3000 Error 

### ISSUE THREAD

**Issue by salmahosni5771** [OneSignal/OneSignal-Android-SDK#522]
**Description:**
I got this "error other Apns 3000 Error"  returned  from APNS  asking for enabling the Push notification on capabilities however i double checked and found it's ticked 

**Environment**
 Xamarin native ios  c#  
VisualStudio 15.7 

**Steps to Reproduce Issue:**
--tried to re produce the certificate using the one signal provisioning  tool 
-- Double checked the Push notification is enabled in the whole Project 
-- Added the asp-Environment to the Entitlement.plist

**Comment by jkasten2** [comment]
@salmahosni5771 This error is iOS not Android related. Also since this is an error you are seeing in Xamarin it best fits the [OneSignal-Xamarin-SDK)(https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues) repository so going to close this issue for off topic.

However I believe what you need to do is sync your profile in Xcode so the new provisioning profile syncs to your system. Please open a ticket in the link above if this doesn't help.
