### ISSUE TITLE
Crashes  on com.onesignal.OneSignal.registerUserTask

### ISSUE THREAD

**Issue by baole** [OneSignal/OneSignal-Android-SDK#567]
Crashes happen on our production app. Here is logs from Crashlytics

http://crashes.to/s/ee2c756eaf5

**Comment by jkasten2** [comment]
@baole Thanks for reporting, this is the reported stacktrace from the crash.

```java
Fatal Exception: java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:162)
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:145)
       at com.onesignal.OneSignal.registerUserTask(Unknown Source)
       at com.onesignal.OneSignal.access$2300(Unknown Source)
       at com.onesignal.OneSignal$7.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:776)
```

The `android.os.DeadSystemException` exception being thrown is from Android core system being killed. This causes calls to android APIs to fail as noted below.
https://stackoverflow.com/a/44395215/1244574

I noticed that most of the crashes in you report are from a  HUAWEI devices. There could be a issue with these devices since they will be running a modified version of Android. The source this Android core crash would be hard to pin point but I don't believe this could be trigged by OneSignal.

**Comment by jkasten2** [comment]
@baole I don't believe the Android Core crash is related to OneSignal. Feel free reply if I am mistaken and we can take a 2nd look.

**Comment by shefich** [comment]
Also happens in my project.

Stacktrace:
`Fatal Exception: java.lang.RuntimeException
Package manager has died
android.app.ApplicationPackageManager.getPackageInfo (ApplicationPackageManager.java:134)
com.onesignal.OneSignal.registerUserTask (OneSignal.java:1521)
com.onesignal.OneSignal.access$1500 (OneSignal.java:86)
com.onesignal.OneSignal$10.run (OneSignal.java:1495)
java.lang.Thread.run (Thread.java:818)

Caused by android.os.DeadObjectException
android.os.BinderProxy.transactNative (Binder.java)
android.os.BinderProxy.transact (Binder.java:503)
android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo (IPackageManager.java:2163)
android.app.ApplicationPackageManager.getPackageInfo (ApplicationPackageManager.java:129)
com.onesignal.OneSignal.registerUserTask (OneSignal.java:1521)
com.onesignal.OneSignal.access$1500 (OneSignal.java:86)
com.onesignal.OneSignal$10.run (OneSignal.java:1495)
java.lang.Thread.run (Thread.java:818)`

Unity 2021.3.23
OneSignal 3.0.10
