### ISSUE TITLE
How to show notification badge On App Icon in IONIC

### ISSUE THREAD

**Issue by gauravAbs** [OneSignal/OneSignal-Android-SDK#568]
How to show notification badge On App Icon in IONIC,my local notification code is working fine but not working in app icon notification counter, please see my example.
Example [Link1](https://i.stack.imgur.com/DE2bA.jpg)

**Comment by jkasten2** [comment]
@gauravAbs On Android, OneSignal sets badges automatically if the Android launcher support it
https://documentation.onesignal.com/docs/appearance#section-setting-and-clearing-badge-numbers

The following ones that are supported are Sony, Samsung, LG, HTC, Xiaomi, Huawei, ASUS, ZUK, OPPO, ADW, APEX, and NOVA. Also Android Pixel devices running Android Oreo, however these show as notification dots instead of a number.

**Comment by jkasten2** [comment]
@gauravAbs Let us know if this does not cover the answer to your question.

**Comment by gauravAbs** [comment]
yes badges automatically supported but some mobile models are not supported. thanks for replay

**Comment by jkasten2** [comment]
@gauravAbs Unfortunately if the Android launcher does not support badges there isn't anything that can be done. The only way it would work on these devices is if they used one of the supported 3rd party launchers from the Google Play store.

OneSignal uses the [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) library which supports most launchers. I didn't see any mention of Gionee mobile or Lyf mobile so I recommend creating a new ticket to ask if these launcher support badges and if they can add support for them.
