### ISSUE TITLE
Reliable way to send notifications to devices with battery optimisation that kills background processes

### ISSUE THREAD

**Issue by ezeinis** [OneSignal/OneSignal-Android-SDK#605]
Hello, I have implemented one signal at 2 different applications and the customer complained about not receiving any notifications. After many hours of digging i found out about that new android 8 feature on some manufacturers where all the apps are by default optimized for battery usage. The question is that, is it possible to send reliably notifications to those manufacturers as well (android 8+ oneplus, samsung, etc.)?

**Comment by jkasten2** [comment]
@ezeinis The changes in Android Oreo such as background execution limits don't effect the reliably of FCM/GCM notifications. The is because even if the app is closed the "Google Play services" app will start the app in the background to process the message. As long as the app hasn't been force killed / stopped (swiping away the app is a normal close) there won't be an issue with the restarting of your app in the background.

There are some manufactures that customize Android which do create issues with either delays or messages to never get to your app. I recommend checking out the following OneSignal blog post for details on the changes that some manufactures have made to Android on their devices.
https://onesignal.com/blog/manufacturers-interfere-with-reliable-notifications/
