### ISSUE TITLE
SERVICE_NOT_AVAILABLE oneSignal ?

### ISSUE THREAD

**Issue by sealiasheq** [OneSignal/OneSignal-Android-SDK#620]
I have bellow error on some android device:

```
09-01 19:38:29.823 10447-10447/lib.finder.ir.openip E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.onesignal.OneSignalSyncServiceUtils.cancelSyncTask
09-01 19:38:29.823 10447-10447/lib.finder.ir.openip W/dalvikvm: VFY: unable to resolve check-cast 80 (Landroid/app/job/JobScheduler;) in Lcom/onesignal/OneSignalSyncServiceUtils;
09-01 19:38:29.823 10447-10447/lib.finder.ir.openip E/dalvikvm: Could not find class 'android.app.job.JobInfo$Builder', referenced from method com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob
09-01 19:38:29.823 10447-10447/lib.finder.ir.openip W/dalvikvm: VFY: unable to resolve new-instance 77 (Landroid/app/job/JobInfo$Builder;) in Lcom/onesignal/OneSignalSyncServiceUtils;
09-01 19:38:29.823 10447-10447/lib.finder.ir.openip D/dalvikvm: VFY: replacing opcode 0x22 at 0x0016
    DexOpt: unable to opt direct call 0x01ba at 0x22 in Lcom/onesignal/OneSignalSyncServiceUtils;.scheduleSyncServiceAsJob
```

For example `PadFone T00C (4.3)`.

<img width="1440" alt="screen shot 2018-09-01 at 7 44 27 pm" src="https://user-images.githubusercontent.com/20620859/44947250-8bf35780-ae1f-11e8-801c-5ad09240895a.png">

**Comment by jkasten2** [comment]
@sealiasheq Thanks for details. The `SERVICE_NOT_AVAILABLE` is thrown from the Firebase / Google play services library. This happens when the "Google Play services" app does not response or runs into some error when getting a push token. There isn't anything the app developer can do, getting this errors means the device will have being other issues with Google services
https://stackoverflow.com/a/17189160/1244574


The `JobScheduler` warning from the logcat you posted is normal. The class is not available on old versions of but this SDK correctly handle this.
