### ISSUE TITLE
OneSignal In-App Service never unbinds

### ISSUE THREAD

**Issue by mwaked301** [OneSignal/OneSignal-Android-SDK#668]
I made a application which uses in-app purchases, and I was handling the in-app purchase service to shutdown as soon as you close the app. I discovered that OneSignal, is keeping that service running through "TrackGooglePurchase" function in those two lines

         if (iapEnabled == PackageManager.PERMISSION_GRANTED)
            IInAppBillingServiceClass = Class.forName("com.android.vending.billing.IInAppBillingService");

So please let me know one of the following:-
1. How I can close the In-AppBillingService which Onesignal keeps running? 
2. Or how to disable Onesignal from tracking my purchases, so it doesn't effect my In-AppBillingService 

Thank you

**Comment by marab2** [comment]
@jkasten2 I had the same problem here, I can see a memory consuming starting by 70MB and ending up 300MB by Google In-App Billing services. We really appreciate your help to solve this ASAP.

**Comment by mwaked301** [comment]
@jkasten2 after checking i found that this is consuming 300mb of old devices which makes the device laggy too much

**Comment by jkasten2** [comment]
@mwaked301 @marab2 I have seen the "Google Play services" app (com.google.android.gms) take up 300MB on devices that have a 4GB of RAM as well. Even without it's purchase service running. I believe the amount of memory GMS will use depends on the device as on lower memory devices it will stop or free up some space in each of it's services. On lower end devices it might only be around 50MB.

Since the "Google Play services" app will create multiple services and each will have a set of services it's not possible to see exactly how much memory the purchases service is specifically taking. This is only a guess but the purchase service would probably take about 10MB of RAM.

We will still look into cleaning up the binding when it isn't needed but I don't believe this is an urgent issue.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
