### ISSUE TITLE
Outdated Android Support Library with Android 8.0 devices with Eclipse SDK

### ISSUE THREAD

**Issue by trungnguyennam** [OneSignal/OneSignal-Android-SDK#674]
**Description:**

Outdated Android Support Library with Android 8.0 (and above) devices with Eclipse SDK

**Environment**

1. What version of the Android SDK are you using? Eclipse + Sample's targetSDK27 
2. How did you add the SDK to your project (eg. maven) I use the lastest OneSignal Eclipse sample  in 3.10.3 Release

**Steps to Reproduce Issue:**

1. Add the OneSignal SDK to your project
  2. Place your App ID in the application's gradle file
  3. When i got this [warning](https://drive.google.com/file/d/1MjkN0WYnYXc9IgzrDElVMu1V14cjLIXR/view?usp=sharing), the device is not marked as outdated support library. Otherwise device always marked as outdated. One sample just keep install and uninstall then sometime it got warning 
i tried with Mi A2 device and Google pixel and both were not working

**Anything else:**
I attach OneSignalSample with lastest working google_play_service in [here](https://drive.google.com/drive/folders/1LflpBfABcevdYwf8WPgO8JsftvADVuaS?usp=sharing). This is working since the last issue i reported [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/549)

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@trungnguyennam I highly recommend switching to Android Studio when you can. Google no longer provides .jar files directly for the latest versions of their libraries, instead they are .aar files. As well as their build tools are no longer being updated for Eclipse.

The error means your Android Support Library is out of date. You will need to use 27.0.0 or newer since you are using targetSDK 27.  Google split the library into parts in revision 24 so you may need to download each part. The one needed for OneSignal is `support-compat`
https://mvnrepository.com/artifact/com.android.support/support-compat/28.0.0
You can download and extract the .jar file from the .aar file.

**Comment by jkasten2** [comment]
@trungnguyennam We will look into updating our Eclipse example. Google is moving from the Android Support Library to AndroidX. We plan to drop support for Eclipse when we switch to this new library.

**Comment by trungnguyennam** [comment]
@jkasten2 i had tried to update support-compat v28 and v27.1.1 but i still got outdated device. If i remove support-compat.jar, i will get support library missing. So i think im doing the right thing. Do you have any suggestion?

**Comment by jkasten2** [comment]
@trungnguyennam The issue is related to get those components of the Android Support library setup with your project and isn't a specific issue with OneSignal itself. Google doesn't have any docs on getting these versions of their library setup with ANT or Eclipse.

We have decided to drop support for ANT and Eclipse builds now so sorry we won't be able to help further with this setup issue until you can switch to a Gradle or Android Studio build.

Once you switch over and are still running into any integration issues please open new github issue.
