### ISSUE TITLE
Notification triggers only after opening the application.

### ISSUE THREAD

**Issue by akashMehta-STL** [OneSignal/OneSignal-Android-SDK#695]
**Description:**

Notification triggers only when the user opens the application in some of the devices. In many cases we observe that notification received by user only after opening the application since that notification is broadcasted 1 or 2 days ago as per the below screenshot. 

![screenshot_20181231-104527](https://user-images.githubusercontent.com/26703407/50570308-c0662880-0dab-11e9-8c6a-ad6478c8ac5d.png)

**Devices**
This issue is faced on mostly Samsung and One Plus devices everytime. 

**Steps to Reproduce Issue:**

1. Put application on the ideal state for more than hour.
2. Send dummy notification from one signal.
3. User will not receive the notification then.
3. All notifications will be recieved only after opening the application.

**Anything else:**

As one signal configuration we followed the documentation provided  [In Documentation](https://documentation.onesignal.com/docs/android-sdk-setup)

**Comment by jkasten2** [comment]
@akashMehta-STL Thanks for the details, the issue you are seeing is related to some devices force killing your app or delaying push notifications to optimize battery.

Some models of OnePlus devices will force kill apps after some time which means most Intents including push notifications won't be received until the user reopens the app. To avoid this you can go to 
Settings > Battery > Battery Optimization > Application and set "Don't Optimize" on the device for your app.

For Samsung devices push notifications can be delayed in some cases due to a similar setting.

These issues are detailed with guides on how to fix on the OneSignal's [Notifications Not Shown](https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#section-the-app-is-force-stopped) documentation.
