### ISSUE TITLE
 LAVA and Infinix - Fatal Exception: java.lang.SecurityException ConnectivityService: android.permission.ACCESS_NETWORK_STATE.

### ISSUE THREAD

**Issue by iballan** [OneSignal/OneSignal-Android-SDK#711]
**Description:**

I got this after i updated to the latest Onesignal SDK and published to playstore.

`Fatal Exception: java.lang.SecurityException ConnectivityService: Neither user 10089 nor current process has android.permission.ACCESS_NETWORK_STATE.`

**Environment**

1. OneSignal - 3.10.6
2. Android 7
3. Phone Models: LAVA and Infinix  ( From Fabric dashboard )

**Exception:**

```java
Fatal Exception: java.lang.SecurityException: ConnectivityService: Neither user 10089 nor current process has android.permission.ACCESS_NETWORK_STATE.
       at android.os.Parcel.readException(Parcel.java:1683)
       at android.os.Parcel.readException(Parcel.java:1636)
       at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1207)
       at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:791)
       at com.onesignal.OSUtils.getNetType(OSUtils.java:193)
       at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1256)
       at com.onesignal.OneSignal.access$2300(OneSignal.java:80)
       at com.onesignal.OneSignal$7.run(OneSignal.java:1211)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by jkasten2** [comment]
@iballan It seems the following permission is missing from your app.
`android.permission.ACCESS_NETWORK_STATE`

This isn't a permission the user is prompted for so it should always be available if it is included in your finial `AndroidManifest.xml`. You can check this by selecting your `AndroidManifest.xml` in Android Studio and selecting `Merged Manifest` on the bottom.

Since you noted you are only seeing the crash with LAVA and Infinix device it is possible they are blocking this permission. Either by default or their custom Android build might have some kind of use setting for this. This is something we can look into adding a catch around to prevent a crash on the specific devices.

How many crashes are you seeing with this error?

**Comment by iballan** [comment]
I made sure that  it is not possible to be because the permission is not exists in Manifest.

The number of crashes of this type was :
190 crashes

**Comment by rlavila8713** [comment]
Hy iballan I'm getting the same error, have you solved this.?

**Comment by iballan** [comment]
@rlavila8713 no I did not find a solution. I just updated to the latest sdk version and ignored the error till they fix it.

**Comment by jkasten2** [comment]
Just to keep everyone updated, we do plan to still catch this `SecurityException` as it is a configurable setting in the `AndroidManifest.xml`, even though we default it in. Also since some custom Android build allow this setting to be overridden and we want to make sure our SDK is as compatible where it can be. We don't have a timeline right now on this but it is still on our list

**Comment by rgomezp** [comment]
Closing due to no response
