### ISSUE TITLE
Is ContentText overridable?

### ISSUE THREAD

**Issue by mpetlyuk** [OneSignal/OneSignal-Android-SDK#717]
I wanna to override notification content, as I understand from the doc I should extend from `NotificationExtenderService`, but I can not override `contentText`, for example. Are there some limitations?

```java
public class OneSignalNotificationService extends NotificationExtenderService {

    @Override
    protected boolean onNotificationProcessing(final OSNotificationReceivedResult receivedResult) {
        ...
        OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = new NotificationCompat.Extender() {
            @Override
            public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
                  return builder.setContentText("Test");
            }
        };

           displayNotification(overrideSettings);

        return true;
    }
}
```

**Comment by jkasten2** [comment]
@mpetlyuk Unfortunately overriding the message body of a notification is a bit more involved. You will need to call `build.setStyle()` since Android uses this for the notification content itself. Example:
```java
builder.setStyle(new NotificationCompat.BigTextStyle().bigText("Test"));
```

Note that however this will override big pictures if you have set one on your OneSignal notification. This is because this requires a different `BigPictureStyle` to be set.

If you set `bigText` you should still set `builder.setContentText` as well, so this text still displays for Android 4.0.

**Comment by mpetlyuk** [comment]
Thanks, but it is really confused.
