### ISSUE TITLE
Android: Heads-up notification not showing up when screen is locked. 

### ISSUE THREAD

**Issue by rikinshah23** [OneSignal/OneSignal-Android-SDK#722]
I am using OneSignal android SDK for push-notification. Our goal is to show heads-up notification when screen is locked. Device in test is Samsung S6 Edge with android 7.0 version

I tried setting Priority to 10 and android_visibility.

Also Setup a category on One-Signal console with IMPORTANCE as URGENT and LOCKSCREEN as PUBLIC.

   byte[] byteArray = Encoding.UTF8.GetBytes("{"
                                                      + "\"app_id\": \"" + appId + "\","
                                                      + "\"headings\": {\"en\": \"" + heading + "\"},"
                                                      + "\"contents\": {\"en\": \"" + message + "\"},"
                                                      + "\"include_player_ids\": [" + deviceIds + "],"
                                                      + "\"priority\":10,"
                                                      + "\"ios_badgeType\":\"Increase\","
                                                      + "\"android_visibility\": 1,"
                                                      + "\"android_channel_id\": \"" + android_channel_id + "\","
                                                      + "\"ios_badgeCount\": 1 }");

When screen is locked, phone should light up and show heads-up notification.

Any help is appreciated. Thanks

**Comment by jkasten2** [comment]
@rikinshah23 This is expected behavior. Heads-up notifications show as normal if they are received when on the lock screen. This is how Android itself handles the notification.

There is an "ambient display" setting you can find on some devices to wake the screen when a notification is received. More details here:
https://www.techrepublic.com/article/enable-ambient-display-for-easier-interaction/

However I don't believe the Samsung S6 Edge has this feature.

It is it's urgent that your users see specific notifications as soon as possible using a priority of `10` and also setting the highest on your Notification Channel is your best option. It is up to the device on how it will be displayed based on Android version and the device.

**Comment by rikinshah23** [comment]
@jkasten2 yes I found the same result after digging one signal documents and other articles online. 
Thanks for confirmation.
