### ISSUE TITLE
How to secure access to app_id?

### ISSUE THREAD

**Issue by uj** [OneSignal/OneSignal-Android-SDK#737]
This is just a general question.  

Obviously the Rest API key is private and will not be available to anyone, that's not the question here.  However, what prevents someone who obtains the app_id from using it in an unauthorized way?  For example, knowing the app_id would allow an unauthorized person to register their device with my app_id, and then they could add any tags they want, and therefore they would be included in push notifications that are targeted to certain tag filters.  The app_id would be fairly trivial to obtain for most apps.  Am I missing something here?

**Comment by jkasten2** [comment]
@uj Sorry for the delay, you are correct that some could add a device with just the `app_id`. However if it wasn't subscribed with a valid push token with your FCM project number it won't get any notifications.

If someone extracted their `player_id` from your app's local storage it is possible however someone could set and change their tags. Because of this I recommend not use of tags for anything that is designed with authentication. Tags should be used to Segment users for specific categories of notifications instead.

**Comment by rgomezp** [comment]
Closing due to no response
