### ISSUE TITLE
I am getting this exception on Android 5.1 and below on many devices

### ISSUE THREAD

**Issue by xzamirx** [OneSignal/OneSignal-Android-SDK#750]
Hello i'm also getting this error in a lot of devices when updating, haven't found a work around yet.

Fatal Exception: android.app.RemoteServiceException
Bad notification posted from package {package_name}: Couldn't expand RemoteViews for: StatusBarNotification(pkg={package_name} user=UserHandle{0} id=1 tag=null score=10 key=0|{package_name}|1|null|10130: Notification(pri=1 contentView={package_name}/0x109008d vibrate=null sound=null defaults=0x0 flags=0x10 color=0xffdf3931 actions=1 originalPackageName=N originalUserId=0 vis=PRIVATE))

_Originally posted by @chatup003 in https://github.com/OneSignal/OneSignal-Android-SDK/issues/263#issuecomment-464350131_

Fabric dashboard: https://imgur.com/Z7rhau6

**Comment by xzamirx** [comment]
I had a problem when showing the notifications. I was not using NotificationCompat.Action.Builder for the actions in the PendingIntent thus when i had default actions without icons the app crashed under lollipop

**Comment by jkasten2** [comment]
@xzamirx The crash is most likely due to the icon missing on the device. I recommend setting buttons instead of using custom code to override OneSignal settings on `NotificationCompat` when possible.
https://documentation.onesignal.com/reference#section-action-buttons

Another side effect you would have if you added buttons to your notification with your own `PendingIntent` is that opens would not be counted on the OneSignal dashboard.

Lastly "Bad notification" crashes won't point to a specific line in your app so it could be from any code in your app that creates notifications, not necessary OneSignal.

**Comment by rgomezp** [comment]
Closing due to no response
