### ISSUE TITLE
Outburst of "Given work is not active" crashes after upgrading from 3.11.1 to 3.11.2

### ISSUE THREAD

**Issue by asfdfdfd** [OneSignal/OneSignal-Android-SDK#830]
These crashes appear mostly on Samsung devices with Android 9. I'm attaching one of the stack traces from Crashlytics.

[com.mirrorai.app_issue_crash_5D630BD703B600015836EBE5C513A7D2_DNE_0_v2.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/3538834/com.mirrorai.app_issue_crash_5D630BD703B600015836EBE5C513A7D2_DNE_0_v2.txt)

I could not reproduce it myself as i do not have Samsung with Android 9, but users have pretty stable crash history since update.

3.11.1 has no such crashes at all.

**Comment by CharlieZheng** [comment]
We occur the same issue.

**Comment by ushi3** [comment]
We too.

Maybe.

**com.onesignal**.JobIntentService to fix #644.

https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/JobIntentService.java#L293-L301

But, this was not used to fix #804.
**androidx.core.app**.JobIntentService is used instead of **com.onesignal**.JobIntentService inside `com.onesignal.GcmIntentJobService`.

**Comment by atulgpt** [comment]
I am also experiencing this issue

**Comment by rgomezp** [comment]
Howdy,
This will be fixed in the next release. Cheers

**Comment by hanilozmen** [comment]
The issue has just shown up after we updated to v3.11.4 from v3.10.8 by the way.
Although there are only 200 sessions for the new version of our app, there is one crash by a Xiaomi Redmi 5 Plus (OS version 8 ).

**Comment by rgomezp** [comment]
This wasn't included in 3.11.4. Our apologies. We will make sure this is in the next release
