### ISSUE TITLE
Project Sync Fails When Including OneSignal

### ISSUE THREAD

**Issue by simon-the-canadian** [OneSignal/OneSignal-Android-SDK#998]
**Description:**
As on yesterday, my app build sync fails when including OneSignal. I've tried updating to version `3.13.2` but I have the same problem. There are certain Google Play dependencies that OneSignal is pulling in that looks like they aren't available anymore. I can fix the issue by forcing the app to use the newer version of those libraries.

**Environment**
Version: 3.13.2

`classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'`
`implementation 'com.onesignal:OneSignal:3.13.2'`

**Issue**
When performing a project sync I get the following error:
```
Could not resolve com.google.firebase:firebase-messaging:[10.2.1, 17.3.99].
Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.0, 16.0.99].
Could not resolve com.google.firebase:firebase-iid:[20.0.0].
Could not resolve com.google.android.gms:play-services-base:[10.2.1, 16.1.99].
```

This is a temporary workaround to get my project to sync in my app build.gradle file:
```
configurations.all {
    resolutionStrategy {
        //need to force dependencies to newer version because OneSignal is using older versions that are no longer available
        force 'com.google.android.gms:play-services-ads-identifier:17.0.0'
        force 'com.google.android.gms:play-services-base:17.2.1'
        force 'com.google.android.gms:play-services-ads-identifier:17.0.0'
        force 'com.google.firebase:firebase-messaging:20.1.5'
    }
}
```

**Comment by rgomezp** [comment]
Howdy,
The OneSignal Gradle Plugin should resolve these dependency issues automatically. This tells me that somehow it isn't doing its job. 

Please make sure you have configured it in your grade file as follows:
```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}
```

**Comment by AmirHosseinJ** [comment]
hi
same problem

Failed to resolve: fragment Affected Modules: app |  
-- | --



Failed to resolve: cardview Affected Modules: app |  
-- | --

**Comment by asfdfdfd** [comment]
As i understand onesignal gradle plugin — it tries to downgrade project libraries, right? Also i've tried to add gradle plugin to my project couple of times and it throws cryptic errors on every attempt. I see this gradle plugin as pretty opaque thing that does some unknown magick.

Do you have an opportunity to just update dependencies for onesignal? They are pretty dated as i could see [here](https://mvnrepository.com/artifact/com.onesignal/OneSignal/3.13.2).

**Comment by jkasten2** [comment]
@simon-the-canadian @AmirHosseinJ Can you provide the full error that Android Studio is showing what you build? Google doesn't remove old libraries so they should still be found.

@asfdfdfd [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) will in almost call cases upgrade instead of downgrade.
Most of the upgrade definitions can be found at [GradleProjectPlugin.groovy#L121-L229](https://github.com/OneSignal/OneSignal-Gradle-Plugin/blob/0.12.7/src/main/groovy/com/onesignal/androidsdk/GradleProjectPlugin.groovy#L121-L229).
There are unit tests that explain the cases the plugins fixes as well in [MainTest.groovy](https://github.com/OneSignal/OneSignal-Gradle-Plugin/blob/master/src/test/groovy/com/onesignal/androidsdk/MainTest.groovy)

We will be updating to AndroidX from the Android Support Library in our next major release 4.0.0) that is being actively worked on. We will be updating Firebase and Google dependencies as well in the major release. AndroidX is a breaking change so we can't upgrade to it in a minor version.

**Comment by asfdfdfd** [comment]
@jkasten2 thanks! i'll look into details.

**Comment by Anitaislam** [comment]
fixing problem can not stable

**Comment by Anitaislam** [comment]
up dates version

**Comment by jkasten2** [comment]
@simon-the-canadian We have uncovered a bug with Gradle 5.6.4 (default when using Android Studio 3.6.3) where if you have any invalid or some 3rd party repositories it will fail to find some dependencies.
Examples include:
  * `http://jcenter.bintray.com` it should be https` as they no longer accept `http`
  * `https://sdk.uxcam.com/android/` - Unknown issue with this 3rd party repository with Gradle 5.6.4.

You can look for these issues and / or upgrade to Gradle 6.0+ resolve them.
To upgrade Gradle update the version number in your project's gradle\wrapper\gradle-wrapper.properties file.

```gradle
distributionUrl=https\://services.gradle.org/distributions/gradle-6.0-all.zip
```

**Comment by simon-the-canadian** [comment]
@jkasten2 thank you for the information. You are right, uxam was the culprit and updating to Gradle 6 fixed my issue. Sorry to take up your time with an issue that ended up not being OneSignal related.

**Comment by jkasten2** [comment]
@simon-the-canadian No problem, it seemed to point to OneSignal due to the dependencies errors. Glad I as was able to help.

If you are using uxcam I would recommend point out the issue to them with their `https://sdk.uxcam.com/android/` repo causing build / sync issues with Gradle 5.6.4 with OneSignal and possibly other SDKs.

Closing as resolved.
